### PR TITLE
Add compound peastash output

### PR DESCRIPTION
**Pull request by jiop**
Hello,

This MR adds a compound peastash output allowing to set multiple outputs at once.

### CODE REVIEW

**Comment by jiop** [comment]
> What's the reason behind adding this to `peastash` itself instead of having this be part of your app's configuration?
I would like to share this output across multiple apps but if you think it doesn't belong into the library, I can find other ways to share it.

**Comment by jarthod** [comment]
@elhu we're adding in our app a new output format with a custom output and we need this plumbing part to have both output. As this one is not specific to our output we though it could benefit other people but as you prefer ;)
(If we decide to keep it here it needs some Readme and specs though @jiop)

**Comment by jiop** [comment]
I'm closing this MR in favor of an internal library as this output doesn't really belongs here.

**Comment by elhu** [comment]
@jarthod I think it makes more sense this way. Nonetheless, thanks a lot for the contribution!

**Pull request closed without merging**
